#!/usr/bin/env bash

# Read config options
export ICLOUD_USERNAME=$(bashio::config 'icloud_username')
export ICLOUD_PASSWORD=$(bashio::config 'icloud_password')
export ICLOUD_CALENDAR=$(bashio::config 'icloud_calendar')
export ICAL_URL=$(bashio::config 'ical_url')
export SYNC_INTERVAL=$(bashio::config 'sync_interval')

python -m ical_sync.main
